name: DrcomoAttributeBinder
version: '1.0'
main: com.baimo.attributebinder.DrcomoAttributeBinder
api-version: '1.20'
depend: [DrcomoCoreLib, PlaceholderAPI, MythicLib, MMOItems]
commands:
  drcomoattributebinder:
    description: 属性加成管理
    usage: /drcomoattributebinder <give|replace|remove|list|reload|flush>
    aliases: [abb, attributeBinder, drcomoattributebinder]
permissions:
  drcomoattributebinder.*:
    description: 所有 DrcomoAttributeBinder 权限
    children:
      drcomoattributebinder.admin: true
      drcomoattributebinder.give: true
      drcomoattributebinder.remove: true
      drcomoattributebinder.list: true
      drcomoattributebinder.replace: true
  drcomoattributebinder.admin:
    description: 重载与写库权限
    default: op
  drcomoattributebinder.give:
    description: 使用 /ab give
    default: op
  drcomoattributebinder.remove:
    description: 使用 /ab remove
    default: op
  drcomoattributebinder.list:
    description: 使用 /ab list
    default: true
  drcomoattributebinder.replace:
    description: 使用 /ab replace
    default: op
